---
abstract: 'Helper functions for op tree manipulation'
author:
  - 'Josh Jore <jjore@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::Depends: 0.302
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
keywords:
  - 'op tree'
  - 'perl internals'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Utils
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  Scalar::Util: 0
  Task::Weaken: 0
  Test::More: 0
  perl: 5.006
resources:
  repository: http://github.com/jbenjore/B-Utils/tree
version: 0.22
