--- #YAML:1.0
name:                B-Utils
version:             0.06
abstract:            Helper functions for op tree manipulation
license:             perl
author:              
    - Joshua b. Jore <jjore@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
