---
abstract: 'Helper functions for op tree manipulation'
author:
  - 'Josh Jore <jjore@cpan.org>'
build_requires:
  Test::More: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Utils
requires:
  B: 0
  Carp: 0
  DynaLoader: 0
  Exporter: 0
  List::Util: 0
  Scalar::Util: 0
  perl: 5.006
  subs: 0
  vars: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=B-Utils
  homepage: http://search.cpan.org/dist/B-Utils
  repository: git://github.com/jbenjore/b-utils.git
version: 0.14
