--- #YAML:1.0
name:               B-Utils
version:            0.11
abstract:           Helper functions for op tree manipulation
author:
    - Joshua b. Jore <jjore@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::CBuilder:  0
    ExtUtils::Depends:   0.302
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:            0
    ExtUtils::CBuilder:  0
    perl:                5.006
    Scalar::Util:        0
    Task::Weaken:        0
    Test::More:          0
resources:
    repository:  http://github.com/jbenjore/B-Utils/tree
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - op tree
    - perl internals
